import json
import os
import shutil
import subprocess
import tempfile
import textwrap
import unittest

from neosloc.cli import analyze
from neosloc.detectors.legibility import _cycles
from neosloc.repo import Repo
from neosloc.specs import openapi_operations

OPENAPI_V1 = textwrap.dedent("""\
    openapi: 3.0.0
    info:
      title: t
      version: 1.0.0
    paths:
      /v1/items:
        get:
          summary: list
        post:
          summary: create
      /v1/items/{id}:
        delete:
          summary: remove
    components: {}
""")
OPENAPI_V2 = OPENAPI_V1.replace("    delete:\n      summary: remove\n",
                                "    get:\n      summary: fetch\n")
assert OPENAPI_V2 != OPENAPI_V1


class Fixture(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.dir)

    def write(self, rel, text):
        path = os.path.join(self.dir, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(text)

    def git(self, *args):
        subprocess.run(["git", "-C", self.dir, *args], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    def commit(self, msg):
        self.git("add", "-A")
        self.git("-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", msg)

    def dim(self, report, key):
        return next(d for d in report.dimensions if d.key == key)


class SpecParsing(unittest.TestCase):
    def test_yaml_operations(self):
        self.assertEqual(openapi_operations(OPENAPI_V1, "api.yaml"),
                         {"GET /v1/items", "POST /v1/items", "DELETE /v1/items/{id}"})

    def test_json_operations(self):
        doc = {"openapi": "3.1.0", "paths": {"/a": {"get": {}, "parameters": []}}}
        self.assertEqual(openapi_operations(json.dumps(doc), "api.json"), {"GET /a"})

    def test_invalid_json(self):
        self.assertIsNone(openapi_operations("{nope", "api.json"))


class Cycles(unittest.TestCase):
    def test_detects_cycle(self):
        self.assertEqual(_cycles({("a", "b"), ("b", "a"), ("b", "c")}), [["a", "b"]])

    def test_acyclic(self):
        self.assertEqual(_cycles({("a", "b"), ("b", "c")}), [])


class EmptyRepo(Fixture):
    def test_scores_zero(self):
        self.write("notes.txt", "hello")
        r = analyze(self.dir)
        self.assertEqual(self.dim(r, "interface").level, 0)
        self.assertEqual(self.dim(r, "legibility").level, 0)


class Classification(Fixture):
    def test_generated_and_examples_excluded(self):
        self.write("app/main.py", "x = 1\n")
        self.write("static/bundle.js", "var a=1;" * 5000)
        self.write("lib/gen.go", "// Code generated by protoc. DO NOT EDIT.\npackage x\n")
        self.write("examples/demo.py", "print(1)\n")
        self.write("app/specs/models.py", "y = 2\n")
        repo = Repo(self.dir)
        self.assertEqual(sorted(repo.source_files(include_tests=False)),
                         ["app/main.py", "app/specs/models.py"])


class FastAPIService(Fixture):
    def setUp(self):
        super().setUp()
        self.write("app/main.py", textwrap.dedent("""\
            import os
            from fastapi import FastAPI
            from app.models import Item
            app = FastAPI()

            @app.get("/v1/items")
            def list_items() -> list:
                return []

            @app.post("/v1/items")
            def create(item: Item) -> Item:
                return item
        """))
        self.write("app/models.py", "class Item:\n    name: str = os.environ.get('X', '')\n")
        self.write("app/__init__.py", "")
        self.write("tests/test_main.py", "def test_x() -> None:\n    assert True\n" * 20)
        self.write("Dockerfile", "FROM python:3.12\n")
        self.write(".env.example", "X=1\n")
        self.write("uv.lock", "")
        self.write("README.md", "# svc\n")

    def test_interface_generated_contract(self):
        r = analyze(self.dir)
        iface = self.dim(r, "interface")
        self.assertEqual(iface.metrics["route_declarations"], 2)
        self.assertEqual(iface.level, 3)
        self.assertTrue(any(e.signal == "generated-spec" for e in iface.evidence))

    def test_mcp_server_adds_surface(self):
        self.write("app/mcp.py", "from mcp.server.fastmcp import FastMCP\nm = FastMCP('x')\n")
        self.assertEqual(self.dim(analyze(self.dir), "interface").level, 4)

    def test_mcp_client_is_not_a_surface(self):
        self.write("app/mcp.py", "from mcp import ClientSession\n")
        self.assertEqual(self.dim(analyze(self.dir), "interface").level, 3)

    def test_embeddability(self):
        emb = self.dim(analyze(self.dir), "embeddability")
        self.assertIn("container-image", emb.metrics["signals"])
        self.assertIn("env-config", emb.metrics["signals"])

    def test_legibility_typed(self):
        leg = self.dim(analyze(self.dir), "legibility")
        self.assertEqual(leg.metrics["typed_ratio"], 1.0)
        self.assertEqual(leg.metrics["import_cycles"], 0)

    def test_import_cycle(self):
        self.write("app/a.py", "from app import b\n")
        self.write("app/b.py", "from app import a\n")
        leg = self.dim(analyze(self.dir), "legibility")
        self.assertEqual(leg.metrics["import_cycles"], 1)

    def test_lazy_import_is_not_a_cycle(self):
        self.write("app/a.py", "from app import b\n")
        self.write("app/b.py", "def f():\n    from app import a\n")
        leg = self.dim(analyze(self.dir), "legibility")
        self.assertEqual(leg.metrics["import_cycles"], 0)

    def test_json_roundtrip(self):
        json.dumps(analyze(self.dir).to_dict())


class Libraries(Fixture):
    def test_typed_npm_library_is_a_contract(self):
        self.write("package.json", '{"name": "x", "main": "dist/index.js", "types": "dist/index.d.ts"}')
        self.write("src/index.ts", "export const f = (a: number): number => a;\n")
        iface = self.dim(analyze(self.dir), "interface")
        self.assertEqual(iface.level, 3)

    def test_untyped_js_library(self):
        self.write("package.json", '{"name": "x", "main": "index.js"}')
        self.write("index.js", "module.exports = function () {};\n")
        iface = self.dim(analyze(self.dir), "interface")
        self.assertEqual(iface.level, 1)
        self.assertTrue(any("type declarations" in g for g in iface.gaps))

    def test_go_main_only_is_not_a_library(self):
        self.write("go.mod", "module x\n")
        self.write("main.go", "// Copyright x\n\npackage main\nfunc main() {}\n")
        self.write("internal/cli/cli.go", "package cli\nfunc Run() {}\n")
        iface = self.dim(analyze(self.dir), "interface")
        self.assertEqual(iface.metrics["library_api"], [])

    def test_web_app_with_main_is_not_a_library(self):
        self.write("package.json", '{"name": "x", "main": "src/index.js"}')
        self.write("src/index.js", "document.body.innerHTML = '';\n")
        self.write("index.html", "<html></html>")
        self.assertEqual(self.dim(analyze(self.dir), "interface").metrics["library_api"], [])

    def test_testdata_spec_ignored(self):
        self.write("pkg/testdata/api.yaml", OPENAPI_V1)
        self.assertEqual(self.dim(analyze(self.dir), "interface").metrics["spec_files"], 0)


class SpecHistory(Fixture):
    def test_detects_removed_operation(self):
        self.git("init", "-q")
        self.write("api/openapi.yaml", OPENAPI_V1)
        self.write("server.js", "app.get('/v1/items', h)\napp.post('/v1/items', h)\n")
        self.commit("v1")
        self.git("tag", "v1.0.0")
        self.write("api/openapi.yaml", OPENAPI_V2)
        self.commit("drop delete")
        r = analyze(self.dir)
        stab = self.dim(r, "stability")
        self.assertEqual(stab.metrics["spec_operations_removed"], 1)
        self.assertEqual(stab.metrics["semver_tags"], 1)
        self.assertTrue(any("without deprecation" in g for g in stab.gaps))
        iface = self.dim(r, "interface")
        self.assertEqual(iface.metrics["spec_operations"], 3)
        self.assertGreaterEqual(iface.level, 3)


if __name__ == "__main__":
    unittest.main()
