"""Repository access: file inventory, cached reads, git helpers.

Every detector reads the codebase through a single `Repo` so files are walked
and decoded once.
"""
from __future__ import annotations

import os
import re
import subprocess
from functools import lru_cache

from .codeview import code_view, has_ignore_pragma
from typing import Dict, Iterable, Iterator, List, Optional, Pattern

SKIP_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "bower_components", "vendor",
    "venv", ".venv", "env", ".env", "__pycache__", ".tox", ".nox", ".mypy_cache",
    ".pytest_cache", "dist", "build", "target", "site-packages", ".next",
    ".nuxt", "coverage", ".gradle", ".idea", ".vscode", "staticfiles",
    ".claude", ".terraform",
}
MAX_FILE_BYTES = 1_000_000

# Extension -> language. Only languages listed here count as source code.
LANGUAGES = {
    ".py": "python", ".pyi": "python",
    ".js": "javascript", ".mjs": "javascript", ".cjs": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "typescript",
    ".go": "go", ".rs": "rust", ".java": "java", ".kt": "kotlin", ".scala": "scala",
    ".rb": "ruby", ".php": "php", ".cs": "csharp", ".c": "c", ".h": "c",
    ".cc": "cpp", ".cpp": "cpp", ".hpp": "cpp", ".swift": "swift",
    ".ex": "elixir", ".exs": "elixir", ".erl": "erlang", ".clj": "clojure",
    ".pl": "perl", ".pm": "perl", ".sh": "shell", ".lua": "lua", ".dart": "dart",
    ".vue": "vue", ".svelte": "svelte", ".r": "r", ".jl": "julia",
}
STATICALLY_TYPED = {"go", "rust", "java", "kotlin", "scala", "csharp", "c", "cpp",
                    "swift", "dart", "typescript"}

TEST_PATH_RE = re.compile(
    r"(^|/)(tests?|__tests__|testing|testdata|test_data)(/|$)|^spec/"
    r"|(^|/)test_[^/]*\.py$|_test\.(py|go|rb|exs?)$"
    r"|\.(test|spec)\.[jt]sx?$|Tests?\.(java|kt|cs)$|_spec\.rb$"
)

EXAMPLE_PATH_RE = re.compile(
    r"(^|/)(examples?|samples?|demos?|docs?|fixtures|benchmarks?"
    r"|vendored|third[_-]?party|external|libs)(/|$)"  # vendored code isn't this project's
)

GENERATED_NAME_RE = re.compile(
    r"(\.min\.(js|css)|[.-]bundle\.js|(^|/)bundle\.js|\.pb\.go|_pb2(_grpc)?\.py|\.generated\.\w+"
    r"|(^|/)migrations/\d{4}_\w+\.py)$"
)
GENERATED_MARK_RE = re.compile(r"@generated|Code generated .* DO NOT EDIT|<auto-generated|DO NOT EDIT")

MANIFEST_RE = re.compile(
    r"(^|/)(requirements[\w.-]*\.(txt|in)|pyproject\.toml|setup\.(py|cfg)|Pipfile|package\.json"
    r"|go\.mod|Cargo\.toml|pom\.xml|build\.gradle(\.kts)?|[\w.]+\.csproj|Gemfile|[\w-]+\.gemspec"
    r"|composer\.json|mix\.exs)$"
)
DOC_RE = re.compile(r"(\.(md|rst|adoc|txt)$|(^|/)docs?/)", re.I)
CONFIG_RE = re.compile(r"\.(ya?ml|toml|ini|cfg|conf|json)$|(^|/)(Dockerfile|Containerfile)[\w.-]*$")
COMMENT_LINE_RE = re.compile(r"^\s*(#|//|/\*|\*|--|;|<!--|%)")

# Rough tokens-per-character ratio for code with current BPE tokenizers.
CHARS_PER_TOKEN = 4.0


def estimate_tokens(text: str) -> int:
    return int(len(text) / CHARS_PER_TOKEN)


class Repo:
    def __init__(self, root: str):
        self.root = os.path.abspath(root)
        if not os.path.isdir(self.root):
            raise NotADirectoryError(self.root)
        self.is_git = self._git_ok()
        self.files: List[str] = sorted(self._list_files())

    # ---- inventory ---------------------------------------------------------

    def _git_ok(self) -> bool:
        try:
            out = self.git("rev-parse", "--show-toplevel")
        except (OSError, subprocess.CalledProcessError):
            return False
        return bool(out.strip())

    def _list_files(self) -> Iterator[str]:
        if self.is_git:
            out = self.git("ls-files", "-co", "--exclude-standard", "-z")
            candidates: Iterable[str] = (p for p in out.split("\0") if p)
        else:
            candidates = self._walk()
        for rel in candidates:
            parts = rel.split("/")
            if any(p in SKIP_DIRS for p in parts[:-1]):
                continue
            full = os.path.join(self.root, rel)
            try:
                if not os.path.isfile(full) or os.path.getsize(full) > MAX_FILE_BYTES:
                    continue
            except OSError:
                continue
            yield rel

    def _walk(self) -> Iterator[str]:
        for dirpath, dirnames, filenames in os.walk(self.root):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for f in filenames:
                yield os.path.relpath(os.path.join(dirpath, f), self.root).replace(os.sep, "/")

    # ---- reading -----------------------------------------------------------

    @lru_cache(maxsize=None)
    def read(self, rel: str) -> str:
        try:
            with open(os.path.join(self.root, rel), "rb") as fh:
                data = fh.read()
        except OSError:
            return ""
        if b"\0" in data[:8000]:
            return ""  # binary
        return data.decode("utf-8", errors="replace")

    @lru_cache(maxsize=None)
    def code_text(self, rel: str, keep_regex: bool = False) -> str:
        """Source as content signals should see it: no comments or docstrings and,
        unless keep_regex, regex literals blanked (see codeview)."""
        text = self.read(rel)
        lang = self.language(rel)
        if lang and has_ignore_pragma(text):
            return ""
        return code_view(text, lang, keep_regex) if lang else text

    def exists(self, rel: str) -> bool:
        return rel in self._fileset

    @property
    def _fileset(self) -> set:
        if not hasattr(self, "_fs"):
            self._fs = set(self.files)
        return self._fs

    def glob(self, pattern: str) -> List[str]:
        """Regex match against repo-relative paths."""
        rx = re.compile(pattern)
        return [f for f in self.files if rx.search(f)]

    def grep(self, pattern: Pattern, files: Optional[Iterable[str]] = None,
             limit: Optional[int] = None, keep_regex: bool = False) -> Dict[str, int]:
        """Return {path: match_count} for files whose text matches `pattern`.

        Source files are matched through their code view, so comments,
        docstrings and (unless keep_regex) regex literals don't count."""
        hits: Dict[str, int] = {}
        for rel in files if files is not None else self.source_files():
            if MANIFEST_RE.search(rel):
                text = self.dependency_text(rel)
            elif self.language(rel):
                text = self.code_text(rel, keep_regex)
            else:
                text = self.read(rel)
            n = len(pattern.findall(text))
            if n:
                hits[rel] = n
                if limit and len(hits) >= limit:
                    break
        return hits

    # ---- classification ----------------------------------------------------

    @staticmethod
    def language(rel: str) -> Optional[str]:
        return LANGUAGES.get(os.path.splitext(rel)[1].lower())

    @staticmethod
    def is_test(rel: str) -> bool:
        return bool(TEST_PATH_RE.search(rel))

    def is_generated(self, rel: str) -> bool:
        """Generated or minified code: nobody edits it, so it isn't change surface."""
        if GENERATED_NAME_RE.search(rel):
            return True
        text = self.read(rel)
        if GENERATED_MARK_RE.search(text[:1000]):
            return True
        lines = text.count("\n") + 1
        return len(text) > 20_000 and len(text) / lines > 300  # minified

    @staticmethod
    def is_example(rel: str) -> bool:
        return bool(EXAMPLE_PATH_RE.search(rel))

    def source_files(self, include_tests: bool = True) -> List[str]:
        """All source files, or with include_tests=False only product code
        (no tests, examples, docs or fixtures)."""
        key = "_src_all" if include_tests else "_src_notest"
        if not hasattr(self, key):
            out = []
            for f in self.files:
                if not self.language(f) or self.is_generated(f):
                    continue
                if not include_tests and (self.is_test(f) or self.is_example(f)):
                    continue
                out.append(f)
            setattr(self, key, out)
        return getattr(self, key)

    def manifests(self) -> List[str]:
        return [f for f in self.files if MANIFEST_RE.search(f) and not self.is_test(f)]

    def dependency_text(self, rel: str) -> str:
        """A manifest's text with transitive entries removed (go.mod `// indirect`),
        so only what the project chose to depend on is matched."""
        text = self.read(rel)
        if rel.endswith("go.mod"):
            text = "\n".join(l for l in text.splitlines() if "// indirect" not in l)
        return text

    def doc_files(self) -> List[str]:
        return [f for f in self.files if DOC_RE.search(f) and not self.language(f)]

    def config_files(self) -> List[str]:
        return [f for f in self.files if CONFIG_RE.search(f) and not self.is_test(f)]

    def sloc(self, rel: str) -> int:
        """Physical source lines: non-blank, not comment-only (sloccount-like)."""
        return sum(1 for line in self.read(rel).splitlines()
                   if line.strip() and not COMMENT_LINE_RE.match(line))

    # ---- git ---------------------------------------------------------------

    def git(self, *args: str) -> str:
        return subprocess.run(
            ["git", "-C", self.root, *args],
            check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        ).stdout.decode("utf-8", errors="replace")

    def git_safe(self, *args: str) -> str:
        if not self.is_git:
            return ""
        try:
            return self.git(*args)
        except (OSError, subprocess.CalledProcessError):
            return ""
