name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - if: matrix.python != '3.8'
        run: pip install anthropic
      - run: python -m unittest discover -v -s tests -t .
      - run: python -m neosloc .
